Home learning project week 3: numpy in data analysis

In [1]:
import numpy as np

Q1. creating 1D array from 0 to 9, shown below

In [2]:
num = np.array([0,1,2,3,4,5,6,7,8,9])
print(num)

[0 1 2 3 4 5 6 7 8 9]


Q2. Creating a 3×3 NumPy array of all Boolean value Trues, shown below

In [4]:


bool1=np.array([True, True, True, True, True, True, True, True, True])


bool2 = bool1.reshape(3,3)
print(bool2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Q3) Extract all odd numbers from array of 1-10, shown below

In [13]:
num1 =np.array([1,2,3,4,5,6,7,8,9,10])
condition = np.mod(num1, 2)!=0

odd = np.extract(condition, num1)
print(odd)

[1 3 5 7 9]


4.Replace all odd numbers in an array of 1-10 with the value -1
# not sure how to do Q4, ask tutor if get stuck

In [ ]:
replace2=np.append()

In [16]:
replace1=np.place(num1, np.mod(num1, 2)!=0, -1)
print(replace1)


None


Q5.Convert a 1D array to a 2D array with 2 rows, shown below

In [20]:
array1 = np.array([1,2,3,4,5,6,7,8,9,1000,3256,346])
array2 = array1.reshape(2,6)
print(array2)

[[   1    2    3    4    5    6]
 [   7    8    9 1000 3256  346]]


Q6.Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals, shown below

In [28]:
a=np.array([4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52]) # 13 rows
b = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65]) #13 rows

#Stacking array a vertically onto array b, shown below:
stack=np.vstack((a,b))

#creating a new array where each entities in the this array is the sum of a column in the stack array coressponding to its index value
sum_col = np.sum(stack, axis=0)
print("stack=", stack,"sum_col=", sum_col)

# Doing matrix multiplication of array a and b using the dot function, shown below

mult= np.dot(a,b)
print("mult=", mult)


stack= [[ 4  8 12 16 20 24 28 32 36 40 44 48 52]
 [ 5 10 15 20 25 30 35 40 45 50 55 60 65]] sum_col= [  9  18  27  36  45  54  63  72  81  90  99 108 117]
mult= 16380


Extension of home learning project

Q1.Create the following pattern without hardcoding. Use only NumPy  functions.

In [11]:
a=np.array([1,1,1])

b=np.multiply(a, 2)
c=np.multiply(a, 3)

num=np.array([1,2,3])
array = np.hstack((a,b,c,num,num,num))
print("a=",a,"b=", b, "c=", c, "array=", array)

a= [1 1 1] b= [2 2 2] c= [3 3 3] array= [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


Q2 of extension

In [14]:
a1 = np.array([1,2,3,4,5])
b1=np.array([4,5,6,7,8,9])

rep_removed_b1 = np.delete(b1, [0,1])

print("rep_removed_b1=",rep_removed_b1)


 

rep_removed_b1= [6 7 8 9]


Q3 of extension for numpy and data analysis, in page 38 of week 3 powerpoint, shown below

In [18]:
#extracting entities in from index 2 to 4 in array "a" and from index 0 to 3 in array b
a1_extract = np.delete(a1, [0,1])
b1_extract=np.delete(b1, [4,5])
# taking the summ of all entitites in a1_extract
sum1 = np.sum(a1_extract)
sum2= np.sum(b1_extract)
total= sum1+sum2

print("total=", total, "a1_extract=", a1_extract, "b1_extract=", b1_extract)

total= 34 a1_extract= [3 4 5] b1_extract= [4 5 6 7]
